enum Weekday {
    MONDAY
    TUESDAY
    WEDNESDAY
    THURSDAY
    FRIDAY
    SATURDAY
    SUNDAY
}

type DayHours {
    weekday: Weekday!
    closed: Boolean!
    opensAt: String
    closesAt: String
    breakStartsAt: String
    breakEndsAt: String
}

input DayHoursInput {
    weekday: Weekday!
    closed: Boolean!
    opensAt: String
    closesAt: String
    breakStartsAt: String
    breakEndsAt: String
}

input UpdateSalonHoursInput {
    hours: [DayHoursInput!]!
    cancellationNoticeHours: Int!
}

enum ServiceCategory {
    HAIR
    MAKE_UP
    MASSAGE
}

type Service {
    id: ID!
    name: String!
    category: ServiceCategory!
    durationMinutes: Int! @rename(attribute: "duration_minutes")
    priceFeninga: Int! @rename(attribute: "price_feninga")
}

input CreateSalonServiceInput {
    name: String!
    category: ServiceCategory!
    durationMinutes: Int
    priceFeninga: Int!
}

input UpdateSalonServiceInput {
    name: String!
    category: ServiceCategory!
    durationMinutes: Int!
    priceFeninga: Int!
}

type User {
    id: ID!
    email: String!
    emailVerified: Boolean! @method(name: "hasVerifiedEmail")
}

type Salon {
    id: ID!
    name: String!
    cancellationNoticeHours: Int! @rename(attribute: "cancellation_notice_hours")
    hours: [DayHours!]! @method(name: "dayHours")
    services: [Service!]! @method(name: "serviceList")
}

type Query {
    salon(id: ID!): Salon
}

type Mutation {
    login(email: String!, password: String!): User!
    updateSalonHours(salonId: ID!, input: UpdateSalonHoursInput!): Salon
    createSalonService(salonId: ID!, input: CreateSalonServiceInput!): Service
    updateSalonService(id: ID!, input: UpdateSalonServiceInput!): Service
}
