// @ts-nocheck — Node fs is not in the PWA tsconfig; Vitest runs this file.
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { expect, test } from 'vitest'

const src = join(dirname(fileURLToPath(import.meta.url)), '..')

function read(rel: string): string {
  return readFileSync(join(src, rel), 'utf8')
}

test('occupying query asks for snapshot service names', () => {
  const pending = read('graphql/pending.ts')
  expect(pending).toMatch(/query OccupyingBookings\([\s\S]*services \{\s*name\s*\}/)
  expect(pending).toMatch(/query OccupyingBookingsRange\([\s\S]*from: \$from/)
  expect(pending).toMatch(/pendingBookings\(salonId: \$salonId, date: \$date, limit: \$limit\)/)
  expect(pending).toMatch(/proposedStartsAt/)
  expect(pending).toMatch(/proposedWorker/)
})

test('owner home is Kalendar week or Kanban day by ownerView', () => {
  const home = read('pages/OwnerHome.tsx')
  expect(home).toMatch(/rounded-3xl bg-canvas p-4 md:p-6/)
  expect(home).not.toMatch(/shadow-/)
  expect(home).toMatch(/ownerView === 'KANBAN'/)
  expect(home).toMatch(/ownerWeekDays\(date\)/)
  expect(home).toMatch(/from: week\.from, to: week\.to/)
  expect(home).toMatch(/limit: 50/)
  expect(home).toMatch(/OCCUPYING_BOOKINGS_RANGE_QUERY[\s\S]{0,240}cache-and-network/)
  expect(home).toMatch(/SALON_DAY_BOOKINGS_QUERY[\s\S]{0,240}cache-and-network/)
  expect(home).toMatch(/skip: !ownerReady \|\| kanban/)
  expect(home).toMatch(/skip: !ownerReady \|\| !kanban/)
  expect(home).toMatch(/onDate\(shiftOwnerDate\(date, delta\)\)/)
  expect(home).toMatch(/<WeekHeader/)
  expect(home).toMatch(/<DayChips/)
  expect(home).toMatch(/<WeekGrid/)
  expect(home).toMatch(/<KanbanBoard/)
  expect(home).toMatch(/visibleKanbanColumns/)
  expect(home).toMatch(/KanbanColumnToggles/)
  expect(home).toMatch(/owner\.columnsError/)
  expect(home).toMatch(/kanbanGroups\([\s\S]*?, now\)/)
  expect(home).toMatch(/status !== 'REQUESTED'/)
  expect(home).toMatch(/formatPickerDayNumeric/)
  expect(home).toMatch(/weekday\.\$\{/)
  expect(home).toMatch(/owner\.title/)
  expect(home).toMatch(/owner\.pendingFor/)
  expect(home).toMatch(/owner\.noPending/)
  expect(home).toMatch(/onOpen=\{openAside\}/)
  expect(home).toMatch(/owner\.soon/)
  expect(home).toMatch(/owner\.closedDay/)
  expect(home).toMatch(/owner\.noWorkers/)
  expect(home).toMatch(/BOOKING_CUSTOMER_RESPONDED_SUBSCRIPTION/)
  expect(home).toMatch(/BOOKING_RESCHEDULED_SUBSCRIPTION/)
  expect(home).toMatch(/BOOKING_CANCELLED_SUBSCRIPTION/)
  expect(home).not.toMatch(/pollInterval/)
  expect(home).not.toMatch(/WorkerPanel/)
  expect(home).not.toMatch(/@dnd-kit/)
  expect(home).not.toMatch(/useDraggable/)
  expect(home).not.toMatch(/DndContext/)
  expect(home).not.toMatch(/type="date"/)
  expect(home).not.toMatch(/ownerMonthDays/)
  expect(home).not.toMatch(/bg-cell-free/)
  expect(home).not.toMatch(/<table/)
  const shellAt = home.indexOf('<OwnerShell')
  const cardAt = home.indexOf('rounded-3xl bg-canvas p-4 md:p-6')
  expect(shellAt).toBeGreaterThan(-1)
  expect(cardAt).toBeGreaterThan(shellAt)
  expect(home).toMatch(/owner\.accept/)
  expect(home).toMatch(/owner\.decline/)
  expect(home).toMatch(/owner\.propose/)
  expect(home).toMatch(/owner\.keepOriginal/)
  expect(home).toMatch(/ACCEPT_PREFERRED_TIME_MUTATION/)
  expect(home).toMatch(/queueChipInitial/)
  expect(home).not.toMatch(/max-h-/)
  expect(home).not.toMatch(/overflow-y-/)
  expect(home).not.toMatch(/bg-busy-/)
  expect(home).not.toMatch(/bg-cell-booked/)
  const boards = read('components/OwnerBoards.tsx')
  expect(boards).toMatch(/owner\.prevWeek/)
  expect(boards).toMatch(/owner\.nextWeek/)
  expect(boards).toMatch(/onShift\(-7\)/)
  expect(boards).toMatch(/onShift\(7\)/)
  expect(boards).toMatch(/owner\.closed'/)
  expect(boards).toMatch(/bg-pastel-pink/)
  expect(boards).toMatch(/bookings\.status\.TIME_PROPOSED/)
  expect(boards).toMatch(/owner\.noShow/)
  expect(boards).toMatch(/workerDotColor/)
  expect(boards).toMatch(/occupyingClockRange/)
  expect(boards).toMatch(/owner\.kanban\.\$\{column\}/)
  expect(home).toMatch(/setInterval\([\s\S]*60_000/)
  expect(home).toMatch(/occupiedElapsedShare\(ymd, row\.preferredStartsAtLabel/)
  expect(home).not.toMatch(/occupiedElapsedShare\([^)]*reschedule/)
  const occupying = boards.slice(boards.indexOf('function OccupyingCard'), boards.indexOf('export function WeekGrid'))
  expect(boards).toMatch(/role="progressbar"/)
  expect(occupying).toMatch(/ElapsedTrack/)
  expect(occupying).toMatch(/status === 'CONFIRMED'/)
  expect(occupying).not.toMatch(/rescheduleStartsAt/)
  expect(occupying).not.toMatch(/transition/)
  const booking = boards.slice(boards.indexOf('function BookingCard'))
  expect(booking).toMatch(/progress !== undefined/)
  expect(read('pages/OwnerZapisi.tsx')).not.toMatch(/progress=/)
  expect(read('pages/OwnerRequestDetail.tsx')).not.toMatch(/progressbar/)
  expect(read('pages/Homepage.tsx')).not.toMatch(/progressbar/)
})

test('Request Detail has form, read, and bounce; no WorkerPanel', () => {
  const detail = read('pages/OwnerRequestDetail.tsx')
  const cardClass = '<div className="text-ink">'
  const readyAt = detail.indexOf('<Aside')
  expect(readyAt).toBeGreaterThan(-1)
  expect(detail.slice(0, readyAt)).not.toMatch(new RegExp(cardClass))
  expect(detail).not.toMatch(/max-w-xl/)
  expect(detail).not.toMatch(/shadow-/)
  expect(detail).not.toMatch(/md:grid/)
  expect(detail).not.toMatch(/GUEST_COLUMN_CLASS/)
  expect(detail).not.toMatch(/t\('owner\.back'\)/)
  expect(detail).not.toMatch(/from=zapisi/)
  expect(detail).not.toMatch(/SALON_PICKER_DIALOG_CLASS/)
  expect(detail).not.toMatch(/<dialog/)
  expect(detail).not.toMatch(/inert/)
  expect(detail).toMatch(/ownerQueuePath/)
  expect(detail).toMatch(/async function changed\(\) \{\s*await refetchBooking\(\)\s*onChanged\(\)/)
  const acceptFn = detail.slice(detail.indexOf('async function onAccept'), detail.indexOf('async function onPropose'))
  expect(acceptFn).toMatch(/await changed\(\)/)
  expect(acceptFn).not.toMatch(/navigate/)
  const proposeFn = detail.slice(detail.indexOf('async function onPropose'), detail.indexOf('async function onDecline'))
  expect(proposeFn).toMatch(/await changed\(\)/)
  expect(proposeFn).not.toMatch(/navigate/)
  const declineFn = detail.slice(detail.indexOf('async function onDecline'), detail.indexOf('async function onNoShow'))
  expect(declineFn).toMatch(/await changed\(\)/)
  expect(declineFn).not.toMatch(/navigate/)
  expect(detail).toMatch(/ASSIGN_WORKER_MUTATION/)
  expect(detail).toMatch(/freeWorkers/)
  const assignFn = detail.slice(detail.indexOf('async function onAssign'), detail.indexOf('async function onPropose'))
  expect(assignFn).toMatch(/await changed\(\)/)
  expect(assignFn).not.toMatch(/navigate/)
  expect(read('pages/OwnerHome.tsx')).toMatch(/freeWorkers/)
  expect(read('pages/OwnerZapisi.tsx')).not.toMatch(/assignWorker/)
  expect(read('components/OwnerBoards.tsx')).not.toMatch(/assignWorker/)
  expect(detail.split(cardClass).length - 1).toBe(1)
  expect(detail).not.toMatch(/WorkerPanel/)
  expect(detail).not.toMatch(/formatOwnerDayHeading/)
  expect(detail).toMatch(/ownerDetailMode/)
  expect(detail).toMatch(/proposedStartsAt/)
  expect(detail).toMatch(/OCCUPYING_BOOKINGS_QUERY/)
  expect(detail).not.toMatch(/OCCUPYING_BOOKINGS_RANGE_QUERY/)
  expect(detail).toMatch(/PROPOSE_TIME_MUTATION/)
  expect(detail).toMatch(/ACCEPT_PREFERRED_TIME_MUTATION/)
  expect(detail).toMatch(/DECLINE_BOOKING_MUTATION/)
  expect(detail).toMatch(/MARK_NO_SHOW_MUTATION/)
  expect(detail).toMatch(/priorConfirmedBookings/)
  expect(detail).toMatch(/owner\.priorBookings/)
  expect(detail).toMatch(/owner\.noShow/)
  expect(detail).toMatch(/owner\.propose/)
  expect(detail).toMatch(/NOT_REQUESTED/)

  const card = detail.slice(detail.indexOf(cardClass))
  const expiredAt = card.indexOf("mode === 'expired'")
  const bounceAt = card.indexOf("mode === 'bounce'")
  const readAt = card.indexOf("mode === 'read'")
  const formAt = card.indexOf("mode === 'form'")
  const missing = card.slice(0, expiredAt)
  const expiredSlice = card.slice(expiredAt, bounceAt)
  const bounceSlice = card.slice(bounceAt, readAt)
  const readSlice = card.slice(readAt, formAt)
  const formSlice = card.slice(formAt)
  expect(expiredSlice).toMatch(/bookings\.status\.UNANSWERED/)
  expect(expiredSlice).toMatch(/owner\.assistant/)
  expect(expiredSlice).not.toMatch(/PriorMemory/)
  expect(expiredSlice).not.toMatch(/<form/)
  expect(expiredSlice).not.toMatch(/t\('owner\.propose'\)/)
  expect(expiredSlice).not.toMatch(/t\('owner\.accept'\)/)
  expect(expiredSlice).not.toMatch(/t\('owner\.decline'\)/)
  expect(missing).toMatch(/NOT_REQUESTED/)
  expect(missing).not.toMatch(/customerName/)
  expect(missing).not.toMatch(/PriorMemory/)
  const header = detail.slice(detail.indexOf('const clock ='), detail.indexOf(cardClass))
  expect(header).toMatch(/occupyingClockRange\(block\.start, block\.durationMinutes\)/)
  expect(header).toMatch(/booking\.proposedStartsAtLabel/)
  expect(header).toMatch(/booking\.preferredStartsAtLabel \?\? t\('owner\.noTime'\)/)
  expect(header).toMatch(/title=\{[^}]*booking\.customerName/)
  expect(bounceSlice).toMatch(/NOT_REQUESTED/)
  expect(bounceSlice).not.toMatch(/PriorMemory/)
  expect(bounceSlice).not.toMatch(/<form/)
  expect(bounceSlice).not.toMatch(/t\('owner\.propose'\)/)
  expect(bounceSlice).not.toMatch(/t\('owner\.accept'\)/)
  expect(bounceSlice).not.toMatch(/t\('owner\.decline'\)/)
  expect(readSlice).toMatch(/PriorMemory/)
  expect(readSlice).not.toMatch(/t\('owner\.propose'\)/)
  expect(formSlice).toMatch(/PriorMemory/)
  expect(formSlice).toMatch(/onPropose/)
  expect(formSlice).toMatch(/t\('owner\.propose'\)/)
  expect(formSlice).toMatch(/onAccept/)
  expect(formSlice).toMatch(/t\('owner\.accept'\)/)
  expect(formSlice).toMatch(/onDecline/)
  expect(formSlice).toMatch(/t\('owner\.decline'\)/)

  const pending = read('graphql/pending.ts')
  expect(pending).toMatch(/query OwnerBooking[\s\S]*priorConfirmedBookings/)
  expect(pending).toMatch(/noShowAt/)
  const i18n = read('i18n.ts')
  expect(i18n).toMatch(/back: 'Nazad'/)
  expect(i18n).toMatch(/NOT_REQUESTED: 'Zahtjev više nije na čekanju\.'/)
  expect(i18n).toMatch(/priorBookings: 'Raniji termini'/)
  expect(i18n).toMatch(/priorEmpty: 'Nema ranijih termina\.'/)
  expect(i18n).toMatch(/noShow: 'Nije došao'/)
  expect(read('App.tsx')).toMatch(/path="\/owner\/requests\/:id"/)
})
