// @ts-nocheck — Node fs is not in the PWA tsconfig; Vitest runs this file.
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { expect, test } from 'vitest'

const src = join(dirname(fileURLToPath(import.meta.url)), '..')

function read(rel: string): string {
  return readFileSync(join(src, rel), 'utf8')
}

test('occupying query asks for snapshot service names', () => {
  const pending = read('graphql/pending.ts')
  expect(pending).toMatch(/query OccupyingBookings\([\s\S]*services \{\s*name\s*\}/)
  expect(pending).toMatch(/query OccupyingBookingsRange\([\s\S]*from: \$from/)
  expect(pending).toMatch(/pendingBookings\(salonId: \$salonId, date: \$date, limit: \$limit\)/)
  expect(pending).toMatch(/proposedStartsAt/)
  expect(pending).toMatch(/proposedWorker/)
})

test('owner home is month navigator plus selected-day list', () => {
  const home = read('pages/OwnerHome.tsx')
  expect(home).toMatch(/rounded-lg border border-hairline bg-canvas p-4/)
  expect(home).not.toMatch(/shadow-/)
  expect(home).toMatch(/md:grid md:grid-cols-2/)
  expect(home).toMatch(/occupyingBookingsRange/)
  expect(home).toMatch(/limit: 50/)
  expect(home).toMatch(/owner\.prevMonth/)
  expect(home).toMatch(/owner\.nextMonth/)
  expect(home).toMatch(/formatOwnerMonthTitle/)
  expect(home).toMatch(/shiftOwnerMonth/)
  expect(home).toMatch(/ownerMonthDays/)
  expect(home).toMatch(/weekday\.MONDAY/)
  expect(home).toMatch(/occupyingDotsForDay/)
  expect(home).toMatch(/bg-ink text-canvas/)
  expect(home).toMatch(/formatPickerDayNumeric/)
  expect(home).toMatch(/weekday\.\$\{/)
  expect(home).toMatch(/<details/)
  expect(home).toMatch(/owner\.title/)
  expect(home).toMatch(/\/owner\/requests\//)
  expect(home).toMatch(/owner\.soon/)
  expect(home).toMatch(/owner\.break/)
  expect(home).toMatch(/owner\.empty/)
  expect(home).toMatch(/owner\.closedDay/)
  expect(home).toMatch(/owner\.noWorkers/)
  expect(home).toMatch(/bookings\.status\.TIME_PROPOSED/)
  expect(home).toMatch(/BOOKING_CUSTOMER_RESPONDED_SUBSCRIPTION/)
  expect(home).toMatch(/BOOKING_RESCHEDULED_SUBSCRIPTION/)
  expect(home).toMatch(/BOOKING_CANCELLED_SUBSCRIPTION/)
  expect(home).not.toMatch(/pollInterval/)
  expect(home).not.toMatch(/WorkerPanel/)
  expect(home).not.toMatch(/@dnd-kit/)
  expect(home).not.toMatch(/useDraggable/)
  expect(home).not.toMatch(/DndContext/)
  expect(home).not.toMatch(/type="date"/)
  expect(home).not.toMatch(/formatOwnerDayHeading/)
  expect(home).not.toMatch(/shiftOwnerDate/)
  expect(home).not.toMatch(/owner\.prevDay/)
  expect(home).not.toMatch(/owner\.nextDay/)
  expect(home).not.toMatch(/Danas/)
  expect(home).not.toMatch(/bg-cell-free/)
  expect(home).not.toMatch(/<table/)
  const navAt = home.indexOf('<OwnerNav')
  const cardAt = home.indexOf('rounded-lg border border-hairline bg-canvas p-4')
  expect(navAt).toBeGreaterThan(-1)
  expect(cardAt).toBeGreaterThan(navAt)
  expect(home).toMatch(/owner\.accept/)
  expect(home).toMatch(/owner\.decline/)
  expect(home).toMatch(/owner\.propose/)
  expect(home).toMatch(/owner\.keepOriginal/)
  expect(home).toMatch(/ACCEPT_PREFERRED_TIME_MUTATION/)
  expect(home).toMatch(/bg-surface-soft/)
  expect(home).toMatch(/queueChipInitial/)
  expect(home).not.toMatch(/max-w-xl/)
  expect(home).not.toMatch(/max-h-/)
  expect(home).not.toMatch(/overflow-y-/)
  expect(home).not.toMatch(/bg-busy-/)
  expect(home).not.toMatch(/bg-cell-booked/)
})

test('Request Detail has form, read, and bounce; no WorkerPanel', () => {
  const detail = read('pages/OwnerRequestDetail.tsx')
  const cardClass = 'rounded-lg border border-hairline bg-canvas p-4'
  const readyAt = detail.indexOf('flex-1 px-5 py-8')
  expect(readyAt).toBeGreaterThan(-1)
  expect(detail.slice(0, readyAt)).not.toMatch(new RegExp(cardClass))
  expect(detail).not.toMatch(/max-w-xl/)
  expect(detail).not.toMatch(/shadow-/)
  expect(detail).not.toMatch(/md:grid/)
  expect(detail).not.toMatch(/GUEST_COLUMN_CLASS/)
  expect(detail.indexOf("t('owner.back')")).toBeLessThan(detail.indexOf(cardClass))
  expect(detail.split(cardClass).length - 1).toBe(1)
  expect(detail).not.toMatch(/WorkerPanel/)
  expect(detail).not.toMatch(/formatOwnerDayHeading/)
  expect(detail).toMatch(/ownerDetailMode/)
  expect(detail).toMatch(/proposedStartsAt/)
  expect(detail).toMatch(/OCCUPYING_BOOKINGS_QUERY/)
  expect(detail).not.toMatch(/OCCUPYING_BOOKINGS_RANGE_QUERY/)
  expect(detail).toMatch(/PROPOSE_TIME_MUTATION/)
  expect(detail).toMatch(/ACCEPT_PREFERRED_TIME_MUTATION/)
  expect(detail).toMatch(/DECLINE_BOOKING_MUTATION/)
  expect(detail).toMatch(/MARK_NO_SHOW_MUTATION/)
  expect(detail).toMatch(/priorConfirmedBookings/)
  expect(detail).toMatch(/owner\.priorBookings/)
  expect(detail).toMatch(/owner\.noShow/)
  expect(detail).toMatch(/owner\.propose/)
  expect(detail).toMatch(/NOT_REQUESTED/)

  const card = detail.slice(detail.indexOf(cardClass))
  const bounceAt = card.indexOf("ownerDetailMode(booking.status) === 'bounce'")
  const readAt = card.indexOf("ownerDetailMode(booking.status) === 'read'")
  const formAt = card.indexOf("ownerDetailMode(booking.status) === 'form'")
  const missing = card.slice(0, bounceAt)
  const bounceSlice = card.slice(bounceAt, readAt)
  const readSlice = card.slice(readAt, formAt)
  const formSlice = card.slice(formAt)
  expect(missing).toMatch(/NOT_REQUESTED/)
  expect(missing).not.toMatch(/customerName/)
  expect(missing).not.toMatch(/PriorMemory/)
  expect(bounceSlice.indexOf('customerName')).toBeLessThan(bounceSlice.indexOf('formatSarajevoTime(booking.preferredStartsAt)'))
  expect(bounceSlice).toMatch(/NOT_REQUESTED/)
  expect(bounceSlice).not.toMatch(/PriorMemory/)
  expect(bounceSlice).not.toMatch(/<form/)
  expect(bounceSlice).not.toMatch(/t\('owner\.propose'\)/)
  expect(bounceSlice).not.toMatch(/t\('owner\.accept'\)/)
  expect(bounceSlice).not.toMatch(/t\('owner\.decline'\)/)
  expect(readSlice.indexOf('customerName')).toBeLessThan(readSlice.indexOf('occupyingClockRange'))
  expect(readSlice).toMatch(/PriorMemory/)
  expect(readSlice).not.toMatch(/t\('owner\.propose'\)/)
  expect(formSlice.indexOf('customerName')).toBeLessThan(formSlice.indexOf('formatSarajevoTime(booking.preferredStartsAt)'))
  expect(formSlice).toMatch(/PriorMemory/)
  expect(formSlice).toMatch(/onPropose/)
  expect(formSlice).toMatch(/t\('owner\.propose'\)/)
  expect(formSlice).toMatch(/onAccept/)
  expect(formSlice).toMatch(/t\('owner\.accept'\)/)
  expect(formSlice).toMatch(/onDecline/)
  expect(formSlice).toMatch(/t\('owner\.decline'\)/)

  const pending = read('graphql/pending.ts')
  expect(pending).toMatch(/query OwnerBooking[\s\S]*priorConfirmedBookings/)
  expect(pending).toMatch(/noShowAt/)
  const i18n = read('i18n.ts')
  expect(i18n).toMatch(/back: 'Nazad'/)
  expect(i18n).toMatch(/NOT_REQUESTED: 'Zahtjev više nije na čekanju\.'/)
  expect(i18n).toMatch(/priorBookings: 'Raniji termini'/)
  expect(i18n).toMatch(/priorEmpty: 'Nema ranijih termina\.'/)
  expect(i18n).toMatch(/noShow: 'Nije došao'/)
  expect(read('App.tsx')).toMatch(/path="\/owner\/requests\/:id"/)
})
