// @ts-nocheck — Node fs is not in the PWA tsconfig; Vitest runs this file.
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { expect, test } from 'vitest'

const src = join(dirname(fileURLToPath(import.meta.url)), '..')

function read(rel: string): string {
  return readFileSync(join(src, rel), 'utf8')
}

test('occupying query asks for snapshot service names', () => {
  const pending = read('graphql/pending.ts')
  expect(pending).toMatch(/query OccupyingBookings\([\s\S]*services \{\s*name\s*\}/)
})

test('WorkerPanel spans occupying cells with wrapping job label', () => {
  const panel = read('components/WorkerPanel.tsx')
  expect(panel).toMatch(/rowSpan/)
  expect(panel).toMatch(/break-words/)
  expect(panel).toMatch(/title=\{label\}/)
  expect(panel).toMatch(/text-xs/)
  expect(panel).toMatch(/h-8/)
  expect(panel).not.toMatch(/\bcolSpan\b/)
  expect(panel).not.toMatch(/truncate/)
  expect(panel).not.toMatch(/h-10/)
  expect(panel).not.toMatch(/now-only|now strip|NowStrip/)
  expect(panel).not.toMatch(/role="tab"/)
  expect(panel).toMatch(/bg-cell-booked/)
  expect(panel).toMatch(/text-canvas/)
  expect(panel).toMatch(/bg-cell-proposed/)
  expect(panel).toMatch(/text-ink/)
  expect(panel).toMatch(/bg-cell-free/)
  expect(panel).toMatch(/bg-cell-off/)
  expect(panel).toMatch(/cell:\$\{workerId\}:\$\{time\}/)
  expect(panel).toMatch(/workers\.map/)
  expect(panel).toMatch(/cells\.map/)
  expect(panel).toMatch(/sticky top-12 z-10 bg-canvas/)
  expect(panel).toMatch(/sticky left-0 bg-canvas/)
  expect(panel).toMatch(/overflow-x-auto/)
  expect(panel).not.toMatch(/max-h-/)
  expect(panel).not.toMatch(/overflow-y-/)
  expect(panel).toMatch(/owner\.noWorkers/)
  expect(panel).toMatch(/owner\.closedDay/)
  const tableAt = panel.indexOf('<table')
  expect(panel.indexOf('owner.noWorkers')).toBeLessThan(tableAt)
  expect(panel.indexOf('owner.closedDay')).toBeLessThan(tableAt)
})

test('owner home queue stays above WorkerPanel; Request Detail has no panel', () => {
  const home = read('pages/OwnerHome.tsx')
  const queueAt = home.indexOf('owner.empty')
  const panelAt = home.indexOf('<WorkerPanel')
  expect(queueAt).toBeGreaterThan(-1)
  expect(panelAt).toBeGreaterThan(queueAt)
  expect(home).not.toMatch(/max-w-xl/)
  expect(home).toMatch(/formatOwnerDayHeading/)
  expect(home).toMatch(/rounded-lg border border-hairline bg-canvas p-4/)
  expect(home).not.toMatch(/shadow-/)
  expect(home).toMatch(/sticky top-0 z-20/)
  expect(home).toMatch(/owner\.prevDay/)
  expect(home).toMatch(/owner\.nextDay/)
  expect(home).toMatch(/‹/)
  expect(home).toMatch(/›/)
  expect(home).toMatch(/type="date"/)
  expect(home).toMatch(/shiftOwnerDate/)
  expect(home).not.toMatch(/showPicker/)
  expect(home).not.toMatch(/Danas/)
  expect(home).not.toMatch(/owner\.today/)
  expect(home).not.toMatch(/<svg/)
  expect(home).not.toMatch(/mt-6 block max-w-xs/)
  expect(home).not.toMatch(/autoScroll=\{false\}/)
  expect(home).toMatch(/bg-surface-soft/)
  expect(home).toMatch(/queueChipInitial/)
  expect(home).toMatch(/text-muted/)
  expect(home).toMatch(/owner\.accept/)
  expect(home).toMatch(/owner\.decline/)
  expect(home).toMatch(/owner\.propose/)
  expect(home).toMatch(/owner\.keepOriginal/)
  expect(home).toMatch(/useDraggable/)
  expect(home).toMatch(/ACCEPT_PREFERRED_TIME_MUTATION/)
  const navAt = home.indexOf('<OwnerNav')
  const cardAt = home.indexOf('rounded-lg border border-hairline bg-canvas p-4')
  expect(navAt).toBeGreaterThan(-1)
  expect(cardAt).toBeGreaterThan(navAt)
  const queueUlSticky = home.match(/<ul className="[^"]*sticky/)
  expect(queueUlSticky).toBeNull()
  expect(home).not.toMatch(/max-h-/)
  expect(home).not.toMatch(/overflow-y-/)

  const detail = read('pages/OwnerRequestDetail.tsx')
  expect(detail).not.toMatch(/WorkerPanel/)
  expect(detail).not.toMatch(/formatOwnerDayHeading/)
})
