// @ts-nocheck — Node fs is not in the PWA tsconfig; Vitest runs this file.
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { expect, test } from 'vitest'

const src = join(dirname(fileURLToPath(import.meta.url)), '..')

function read(rel: string): string {
  return readFileSync(join(src, rel), 'utf8')
}

test('ME_QUERY loads salon hours and address; no new GraphQL openNow field', () => {
  const auth = read('graphql/auth.ts')
  expect(auth).toMatch(/query Me \{[\s\S]*salons \{[\s\S]*address[\s\S]*cancellationNoticeHours[\s\S]*hours \{[\s\S]*weekday[\s\S]*closed[\s\S]*opensAt[\s\S]*closesAt[\s\S]*breakStartsAt[\s\S]*breakEndsAt[\s\S]*serviceCategories \{[\s\S]*id[\s\S]*name[\s\S]*services \{[\s\S]*id[\s\S]*name[\s\S]*durationMinutes[\s\S]*priceFeninga[\s\S]*workers \{[\s\S]*id[\s\S]*name/)
  expect(auth).toMatch(/mutation UpdateSalon/)
  expect(auth).toMatch(/mutation UpdateSalonHours/)
  expect(auth).toMatch(/mutation CreateSalonService/)
  expect(auth).toMatch(/mutation UpdateSalonService/)
  expect(auth).toMatch(/mutation CreateSalonServiceCategory/)
  expect(auth).toMatch(/mutation UpdateSalonServiceCategory/)
  expect(auth).toMatch(/mutation DeleteSalonServiceCategory/)
  expect(auth).toMatch(/mutation CreateSalonWorker/)
  expect(auth).toMatch(/mutation UpdateSalonWorker/)
  expect(auth).toMatch(/MeData[\s\S]*cancellationNoticeHours: number/)
  expect(auth).toMatch(/MeData[\s\S]*serviceCategories: \{[\s\S]*id: string[\s\S]*name: string[\s\S]*services: \{[\s\S]*id: string[\s\S]*name: string[\s\S]*durationMinutes: number[\s\S]*priceFeninga: number/)
  expect(auth).toMatch(/MeData[\s\S]*workers: \{[\s\S]*id: string[\s\S]*name: string/)
  expect(auth).toMatch(/mutation AddSalon/)
  expect(auth).not.toMatch(/openNow/)
})

test('App lazy-loads catalog then create then /owner/salons/:id', () => {
  const app = read('App.tsx')
  expect(app).toMatch(/const OwnerSalons = lazy\(/)
  expect(app).toMatch(/const OwnerSalonCreate = lazy\(/)
  expect(app).toMatch(/const OwnerSalonEdit = lazy\(/)
  expect(app).toMatch(/path="\/owner\/salons"/)
  expect(app).toMatch(/path="\/owner\/salons\/create"/)
  expect(app).toMatch(/path="\/owner\/salons\/:id"/)
  expect(app.indexOf('path="/owner/salons"')).toBeLessThan(app.indexOf('path="/owner/salons/create"'))
  expect(app.indexOf('path="/owner/salons/create"')).toBeLessThan(app.indexOf('path="/owner/salons/:id"'))
})

test('OwnerNav Saloni has no salon query and is on every owner overlay', () => {
  const nav = read('components/OwnerNav.tsx')
  expect(nav).toMatch(/OWNER_SALONS_PATH/)
  expect(nav).toMatch(/active === 'salons'/)
  expect(nav).toMatch(/owner\.salons/)
  expect(nav).not.toMatch(/\?salon=/)
  for (const file of [
    'pages/OwnerHome.tsx',
    'pages/OwnerChats.tsx',
    'pages/OwnerStats.tsx',
    'pages/OwnerRequestDetail.tsx',
    'pages/OwnerSalons.tsx',
    'pages/OwnerSalonCreate.tsx',
    'pages/OwnerSalonEdit.tsx',
  ]) {
    expect(read(file), file).toMatch(/<OwnerNav/)
  }
})

test('catalog overlay has boxed shops, header plus, Uredi; not-owner keeps create-salon', () => {
  const page = read('pages/OwnerSalons.tsx')
  expect(page).toMatch(/owner\.notOwner/)
  expect(page).toMatch(/CREATE_SALON_PATH/)
  expect(page).toMatch(/owner\.createSalon/)
  expect(page).toMatch(/owner\.openNow/)
  expect(page).toMatch(/owner\.closedNow/)
  expect(page).toMatch(/salonIsOpenNow/)
  expect(page).toMatch(/ownerSalonEditPath\(row\.id\)/)
  expect(page).toMatch(/ownerSalonCreatePath\(\)/)
  expect(page).toMatch(/aria-label=\{t\('owner\.addSalon'\)\}/)
  expect(page).toMatch(/h-10 w-10/)
  expect(page).toMatch(/owner\.edit/)
  expect(page).toMatch(/\{row\.name\}/)
  expect(page).toMatch(/<ul className="mt-8 max-w-xl space-y-3"/)
  expect(page).toMatch(/border border-hairline p-5/)
  expect(page).toMatch(/border border-hairline bg-canvas px-5/)
  const heading = page.indexOf("t('owner.salons')")
  const plus = page.indexOf("aria-label={t('owner.addSalon')}")
  const phoneNav = page.indexOf('md:hidden')
  const list = page.indexOf('<ul className="mt-8 max-w-xl space-y-3"')
  expect(heading).toBeGreaterThan(-1)
  expect(heading).toBeLessThan(plus)
  expect(plus).toBeLessThan(phoneNav)
  expect(phoneNav).toBeLessThan(list)
  expect(page.slice(page.indexOf('</ul>'))).not.toMatch(/ownerSalonCreatePath/)
  expect(page).not.toMatch(/divide-y divide-hairline/)
  expect(page).not.toMatch(/rounded-lg/)
  expect(page).not.toMatch(/md:grid-cols-2/)
  expect(page).not.toMatch(/<select/)
  expect(page).not.toMatch(/t\('owner\.salon'\)/)
  expect(page).not.toMatch(/\?salon=/)
  expect(page).not.toMatch(/navigate\(/)
})

test('salon edit loads from me.salons; exclusive chips; split Spremi', () => {
  const page = read('pages/OwnerSalonEdit.tsx')
  expect(page).toMatch(/ME_QUERY/)
  expect(page).toMatch(/UPDATE_SALON_MUTATION/)
  expect(page).toMatch(/UPDATE_SALON_HOURS_MUTATION/)
  expect(page).toMatch(/CREATE_SALON_SERVICE_MUTATION/)
  expect(page).toMatch(/UPDATE_SALON_SERVICE_MUTATION/)
  expect(page).toMatch(/salons\.find/)
  expect(page).toMatch(/useState<SalonEditSection>\('info'\)/)
  expect(page).toMatch(/owner\.info/)
  expect(page).toMatch(/flex flex-wrap/)
  expect(page).toMatch(/font-semibold text-ink/)
  expect(page).toMatch(/text-body/)
  expect(page).toMatch(/type="button"/)
  expect(page).toMatch(/hidden/)
  expect(page).toMatch(/border border-hairline p-5/)
  expect(page).not.toMatch(/useSearchParams/)
  expect(page).not.toMatch(/\?tab=/)
  expect(page).not.toMatch(/location\.hash/)
  expect(page).not.toMatch(/window\.confirm/)
  expect(page).not.toMatch(/grid-cols-7/)
  expect(page).not.toMatch(/form className="mt-8 max-w-md/)
  expect(page).not.toMatch(/section className="mt-10 max-w-md/)
  expect(page).toMatch(/owner\.salonName/)
  expect(page).toMatch(/owner\.address/)
  expect(page).toMatch(/salon\.hours/)
  expect(page).toMatch(/weekday\.\$\{day\.weekday\}/)
  expect(page).toMatch(/salon\.closed/)
  expect(page).toMatch(/owner\.opens/)
  expect(page).toMatch(/owner\.closes/)
  expect(page).toMatch(/owner\.break/)
  expect(page).toMatch(/owner\.cancellationNotice/)
  expect(page).toMatch(/owner\.save/)
  expect(page).toMatch(/owner\.INVALID_NAME/)
  expect(page).toMatch(/owner\.INVALID_ADDRESS/)
  expect(page).toMatch(/owner\.INVALID_HOURS/)
  expect(page).toMatch(/owner\.FORBIDDEN/)
  expect(page).toMatch(/salon\.gate\.fallback/)
  expect(page).toMatch(/salon\.services/)
  expect(page).toMatch(/salon\.emptyServices/)
  expect(page).toMatch(/owner\.serviceName/)
  expect(page).toMatch(/owner\.duration/)
  expect(page).toMatch(/owner\.price/)
  expect(page).toMatch(/owner\.addService/)
  expect(page).toMatch(/owner\.INVALID_SERVICE_NAME/)
  expect(page).toMatch(/owner\.INVALID_DURATION/)
  expect(page).toMatch(/owner\.INVALID_PRICE/)
  expect(page).toMatch(/owner\.DUPLICATE_SERVICE_NAME/)
  expect(page).toMatch(/owner\.workers/)
  expect(page).toMatch(/owner\.noWorkers/)
  expect(page).toMatch(/owner\.workerName/)
  expect(page).toMatch(/owner\.addWorker/)
  expect(page).toMatch(/owner\.INVALID_WORKER_NAME/)
  expect(page).toMatch(/owner\.DUPLICATE_WORKER_NAME/)
  expect(page).toMatch(/kmToFeninga/)
  expect(page).toMatch(/feningaToKm/)
  expect(page).toMatch(/createSalonService/)
  expect(page).toMatch(/updateSalonService/)
  expect(page).toMatch(/createSalonWorker/)
  expect(page).toMatch(/updateSalonWorker/)
  expect(page).toMatch(/await createSalonWorker[\s\S]*setName\(''\)[\s\S]*await onSaved/)
  expect(page).toMatch(/await updateSalonWorker[\s\S]*await onSaved/)
  expect(page).toMatch(/durationMinutes\?: number/)
  expect(page).toMatch(/duration\.trim\(\) !== ''/)
  expect(page).toMatch(/CREATE_SALON_SERVICE_CATEGORY_MUTATION/)
  expect(page).toMatch(/UPDATE_SALON_SERVICE_CATEGORY_MUTATION/)
  expect(page).toMatch(/DELETE_SALON_SERVICE_CATEGORY_MUTATION/)
  expect(page).toMatch(/owner\.categoryName/)
  expect(page).toMatch(/owner\.addCategory/)
  expect(page).toMatch(/owner\.deleteCategory/)
  expect(page).toMatch(/owner\.INVALID_CATEGORY_NAME/)
  expect(page).toMatch(/owner\.DUPLICATE_CATEGORY_NAME/)
  expect(page).toMatch(/owner\.CATEGORY_NOT_EMPTY/)
  expect(page).toMatch(/owner\.INVALID_CATEGORY/)
  expect(page).toMatch(/serviceCategoryId/)
  expect(page).toMatch(/selectedCategoryId/)
  expect(page).toMatch(/type="radio"/)
  expect(page).toMatch(/step=\{15\}/)
  expect(page).toMatch(/min=\{15\}/)
  expect(page).toMatch(/active="salons"/)
  expect(page).toMatch(/rounded-md bg-ink/)
  expect(page).toMatch(/type="time"/)
  expect(page).toMatch(/step=\{900\}/)
  expect(page).toMatch(/type="number"/)
  expect(page).toMatch(/toSalonHoursInput/)
  expect(page).toMatch(/hoursAccordionSummary/)
  expect(page).toMatch(/openWeekday/)
  expect(page).toMatch(/useState<string \| null>\(null\)/)
  expect(page).toMatch(/if \(next !== 'hours'\)/)
  expect(page).toMatch(/setOpenWeekday\(null\)/)
  expect(page).toMatch(/openWeekday === day\.weekday/)
  expect(page).toMatch(/<ul className="space-y-3">/)
  expect(page).not.toMatch(/<ul className="[^"]*grid-cols-2/)
  expect(page).not.toMatch(/<ul className="[^"]*md:grid-cols-2/)
  expect(page).not.toMatch(/localStorage/)
  expect(page).not.toMatch(/sessionStorage/)
  expect(page).not.toMatch(/<details/)
  expect(page).toMatch(/flex w-full justify-between/)
  expect(page).toMatch(/'09:00'/)
  expect(page).toMatch(/'17:00'/)
  expect(page).toMatch(/'12:00'/)
  expect(page).toMatch(/'13:00'/)
  expect(page.indexOf('await updateSalon')).toBeGreaterThan(-1)
  expect(page.indexOf('await updateSalon')).toBeLessThan(page.indexOf('await updateSalonHours'))
  expect(page.indexOf("t('salon.services')")).toBeLessThan(page.indexOf("t('owner.workers')"))
  const chipRow = page.slice(page.indexOf('gap-x-4 gap-y-2'), page.indexOf('void onSubmitInfo'))
  expect(chipRow).toMatch(/owner\.info/)
  expect(chipRow).toMatch(/salon\.hours/)
  expect(chipRow).toMatch(/salon\.services/)
  expect(chipRow).toMatch(/owner\.workers/)
  expect(chipRow).not.toMatch(/rounded-md/)
  expect(chipRow).not.toMatch(/rounded-full/)
  expect(chipRow).not.toMatch(/border-b/)
  expect(chipRow).not.toMatch(/badge/)
  const infoSubmit = page.slice(
    page.indexOf('async function onSubmitInfo'),
    page.indexOf('async function onSubmitHours'),
  )
  expect(infoSubmit).toMatch(/await updateSalon/)
  expect(infoSubmit).not.toMatch(/updateSalonHours/)
  expect(infoSubmit).not.toMatch(/createSalonService/)
  expect(infoSubmit).not.toMatch(/updateSalonService/)
  expect(infoSubmit).not.toMatch(/createSalonWorker/)
  expect(infoSubmit).not.toMatch(/updateSalonWorker/)
  const hoursSubmit = page.slice(page.indexOf('async function onSubmitHours'), page.indexOf('async function onAddCategory'))
  expect(hoursSubmit).toMatch(/await updateSalonHours/)
  expect(hoursSubmit).not.toMatch(/await updateSalon\(/)
  expect(hoursSubmit).not.toMatch(/setOpenWeekday/)
  expect(hoursSubmit).not.toMatch(/createSalonService/)
  expect(hoursSubmit).not.toMatch(/updateSalonService/)
  expect(hoursSubmit).not.toMatch(/createSalonWorker/)
  expect(hoursSubmit).not.toMatch(/updateSalonWorker/)
  const hoursList = page.slice(page.indexOf('<ul className="space-y-3">'), page.indexOf("t('owner.cancellationNotice')"))
  expect(hoursList).toMatch(/type="button"/)
  expect(hoursList).toMatch(/hoursAccordionSummary/)
  expect(hoursList).toMatch(/owner\.break/)
  expect(hoursList).not.toMatch(/<svg/)
  expect(hoursList).not.toMatch(/chevron/i)
  expect(hoursList).not.toMatch(/<details/)
  expect(hoursList.indexOf('flex w-full justify-between')).toBeGreaterThan(-1)
  expect(hoursList.indexOf('flex w-full justify-between')).toBeLessThan(hoursList.indexOf('salon.closed'))
  expect(hoursList.indexOf('flex w-full justify-between')).toBeLessThan(hoursList.indexOf('owner.break'))
  const profile = read('pages/SalonProfile.tsx')
  expect(profile).toMatch(/hoursLine/)
  expect(profile).toMatch(/flex justify-between/)
  expect(profile).not.toMatch(/openWeekday/)
  expect(profile).not.toMatch(/hoursAccordionSummary/)
  expect(page).not.toMatch(/OWNER_SALON_QUERY/)
  expect(page).not.toMatch(/salon\(id/)
  expect(page).not.toMatch(/t\('owner\.salon'\)/)
  expect(page).not.toMatch(/<select/)
  expect(page).not.toMatch(/updateSalonDnd/)
  expect(page).not.toMatch(/deleteSalonWorker/)
  expect(page).not.toMatch(/\bdeleteSalonService\b/)
  expect(page).toMatch(/deleteSalonServiceCategory/)
  expect(page).not.toMatch(/\/owner\/salons\/create/)
})

test('add salon overlay form calls addSalon and lands on edit', () => {
  const page = read('pages/OwnerSalonCreate.tsx')
  expect(page).toMatch(/ME_QUERY/)
  expect(page).toMatch(/ADD_SALON_MUTATION/)
  expect(page).toMatch(/owner\.addSalon/)
  expect(page).toMatch(/owner\.salonName/)
  expect(page).toMatch(/owner\.address/)
  expect(page).toMatch(/owner\.save/)
  expect(page).toMatch(/owner\.INVALID_NAME/)
  expect(page).toMatch(/owner\.INVALID_ADDRESS/)
  expect(page).toMatch(/salon\.gate\.fallback/)
  expect(page).toMatch(/active="salons"/)
  expect(page).toMatch(/rounded-md bg-ink/)
  expect(page).toMatch(/ownerSalonEditPath\(id\)/)
  expect(page).toMatch(/CREATE_SALON_PATH/)
  expect(page).toMatch(/owner\.createSalon/)
  expect(page).not.toMatch(/GUEST_COLUMN_CLASS/)
  expect(page).not.toMatch(/t\('owner\.salon'\)/)
  expect(page).not.toMatch(/<select/)
  expect(page).not.toMatch(/updateSalonHours/)
  expect(page).not.toMatch(/createSalonService/)
  expect(page).not.toMatch(/createSalonWorker/)
  expect(page).not.toMatch(/updateSalonDnd/)
})

test('request detail has OwnerNav and no salon switcher', () => {
  const page = read('pages/OwnerRequestDetail.tsx')
  expect(page).toMatch(/<OwnerNav/)
  expect(page).not.toMatch(/t\('owner\.salon'\)/)
  expect(page).not.toMatch(/onSalon/)
})

test('create-salon is unchanged and has no OwnerNav', () => {
  const page = read('pages/CreateSalon.tsx')
  expect(page).not.toMatch(/OwnerNav/)
  expect(page).not.toMatch(/owner\.salons/)
  expect(page).toMatch(/createSalon\.name/)
})

test('edit and home have no add-salon control', () => {
  expect(read('pages/OwnerSalonEdit.tsx')).not.toMatch(/\/owner\/salons\/create/)
  expect(read('pages/OwnerHome.tsx')).not.toMatch(/\/owner\/salons\/create/)
  expect(read('pages/OwnerSalonEdit.tsx')).not.toMatch(/owner\.addSalon/)
  expect(read('pages/OwnerHome.tsx')).not.toMatch(/owner\.addSalon/)
})
