// @ts-nocheck — Node fs is not in the PWA tsconfig; Vitest runs this file.
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { expect, test } from 'vitest'

const src = join(dirname(fileURLToPath(import.meta.url)), '..')

function read(rel: string): string {
  return readFileSync(join(src, rel), 'utf8')
}

test('phone route redirects and does not open the modal', () => {
  const app = read('App.tsx')
  expect(app).toMatch(/const OwnerPhoneBooking = lazy\(/)
  expect(app).toMatch(/path="\/owner\/phone"/)
  const page = read('pages/OwnerPhoneBooking.tsx')
  const redirect = page.slice(page.indexOf('export function OwnerPhoneBooking'))
  expect(redirect).toMatch(/Navigate/)
  expect(redirect).toMatch(/ownerQueuePath/)
  expect(redirect).not.toMatch(/createPhone/)
  expect(redirect).not.toMatch(/showModal/)
  expect(page).not.toMatch(/<TopNav/)
  expect(page).not.toMatch(/<OwnerNav/)
})

test('Zahtjevi opens Telefon as a modal', () => {
  const home = read('pages/OwnerHome.tsx')
  expect(home).toMatch(/owner\.phone\.button/)
  expect(home).toMatch(/setPhoneOpen\(true\)/)
  expect(home).toMatch(/type="button"[\s\S]{0,240}bg-ink px-6/)
  expect(home).not.toMatch(/ownerPhonePath/)
  expect(home).toMatch(/PhoneBookingDialog/)
  expect(home).toMatch(/setPhoneOpen\(false\)/)
  expect(home).toMatch(/onSaved=\{\(saved\) => \{[\s\S]*const savedWeek = ownerWeekDays\(saved\)/)
  expect(home).toMatch(/onSaved=\{\(saved\) => \{[\s\S]*setParams\(ownerSearchParams\(saved/)
  expect(home).toMatch(/refetchQueue\(\{ salonId: salon\.id, date: saved, limit: 50 \}\)/)
  expect(home).toMatch(/refetchDay\(\{ salonId: salon\.id, date: saved, origin: null \}\)/)
  expect(home).toMatch(/refetchRange\(\{ salonId: salon\.id, from: savedWeek\[0\], to: savedWeek\[6\] \}\)/)
  expect(home).not.toMatch(/Zapisi/)
})

test('phone modal is four steps with day chips and quarter pills', () => {
  const page = read('pages/OwnerPhoneBooking.tsx')
  const dialog = page.slice(page.indexOf('export function PhoneBookingDialog'), page.indexOf('export function OwnerPhoneBooking'))
  expect(dialog).toMatch(/SALON_PICKER_DIALOG_CLASS/)
  expect(dialog).toMatch(/showModal/)
  expect(dialog).not.toMatch(/dialogCancelShouldClose/)
  expect(dialog).not.toMatch(/event\.target === dialogRef\.current/)
  expect(dialog).toMatch(/onCancel=\{\(event\) => \{\s*event\.preventDefault\(\)/)
  expect(dialog).toMatch(/salon\.close/)
  const step0 = dialog.slice(dialog.indexOf('step === 0'), dialog.indexOf('step === 1'))
  expect(step0).not.toMatch(/onClose/)
  expect(step0).not.toMatch(/owner\.back/)
  expect(dialog).toMatch(/owner\.phone\.title/)
  expect(dialog).toMatch(/owner\.back/)
  expect(dialog).toMatch(/onClose\(\)/)
  expect(dialog).toMatch(/setServiceIds\(\[\]\)/)
  expect(dialog).toMatch(/setSkipped\(false\)/)
  expect(dialog).not.toMatch(/useSearchParams/)
  expect(dialog).not.toMatch(/params\.get\('date'\)/)
  expect(dialog).toMatch(/owner\.phone\.services/)
  expect(dialog).toMatch(/owner\.phone\.when/)
  expect(dialog).toMatch(/owner\.phone\.worker/)
  expect(dialog).toMatch(/owner\.phone\.caller/)
  expect(dialog).toMatch(/owner\.phone\.next/)
  expect(dialog).toMatch(/owner\.phone\.today/)
  expect(dialog).toMatch(/owner\.phone\.tomorrow/)
  expect(dialog).toMatch(/owner\.phone\.otherDay/)
  expect(dialog).toMatch(/owner\.phone\.noStart/)
  expect(dialog).toMatch(/owner\.phone\.noWorker/)
  expect(dialog).toMatch(/owner\.phone\.note/)
  expect(dialog).toMatch(/SALON_CLOSED/)
  expect(dialog).toMatch(/auth\.name/)
  expect(dialog).toMatch(/auth\.phone/)
  expect(dialog).toMatch(/type="date"/)
  expect(dialog).toMatch(/type="time"/)
  expect(dialog).toMatch(/step=\{900\}/)
  expect(dialog).toMatch(/phoneManualTimeBlock/)
  expect(dialog).toMatch(/phoneQuarterChoices/)
  expect(dialog).toMatch(/owner\.phone\.booked/)
  expect(dialog).not.toMatch(/\bmin=/)
  expect(dialog).not.toMatch(/<select/)
  expect(dialog).toMatch(/aria-pressed/)
  expect(dialog).toMatch(/salon\.loading/)
  expect(dialog).toMatch(/OCCUPYING_BOOKINGS_RANGE_QUERY/)
  const skipAt = dialog.indexOf('phoneSkipDate(today')
  expect(dialog.slice(skipAt - 220, skipAt)).toMatch(/windowRows === undefined/)
  const skipEnd = dialog.indexOf('setSkipped(true)', skipAt)
  expect(dialog.slice(skipAt, skipEnd)).not.toMatch(/setOtherDate/)
  expect(dialog).toMatch(/phoneAfterServiceChange/)
  expect(dialog).toMatch(/phoneWorkerSelection/)
  expect(dialog).toMatch(/serviceIds\.length === 0/)
  expect(dialog).toMatch(/disabled=\{!whenReady\}/)
  expect(dialog).toMatch(/disabled=\{workerId === ''\}/)
  expect(dialog).toMatch(/freeWorkers\.length === 0/)
  expect(dialog).toMatch(/owner\.save/)
  expect(dialog).toMatch(/CREATE_PHONE_BOOKING_MUTATION/)
  expect(dialog).toMatch(/callerPhone: callerPhone\.trim\(\)/)
  expect(dialog).toMatch(/callerNote: callerNote\.trim\(\)/)
  expect(dialog.indexOf('INVALID_CALLER_NAME')).toBeLessThan(dialog.indexOf('createPhone('))
  expect(dialog).toMatch(/onSaved\(saved\)/)
  expect(dialog).not.toMatch(/Nema preference/)
  expect(dialog).toMatch(/salonSeen/)
})

test('request detail phone cancel omits prior bookings', () => {
  const detail = read('pages/OwnerRequestDetail.tsx')
  const cancel = detail.slice(detail.indexOf('function PhoneCancel'))
  expect(cancel).toMatch(/owner\.phone\.cancel/)
  expect(cancel).toMatch(/bookings\.cancelBooking/)
  expect(cancel).toMatch(/owner\.declineCancel/)
  expect(cancel).not.toMatch(/declineReason/)
  expect(cancel).toMatch(/preferredStartsAt/)
  expect(detail).toMatch(/CANCEL_PHONE_BOOKING_MUTATION/)
  expect(detail).toMatch(/origin === 'PHONE'/)
  expect(detail).toMatch(/callerPhone/)
  expect(detail).toMatch(/callerNote/)
  expect(detail).toMatch(/booking\.origin === 'PHONE' \? null/)
})
