// @ts-nocheck — Node fs is not in the PWA tsconfig; Vitest runs this file.
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { expect, test } from 'vitest'

const src = join(dirname(fileURLToPath(import.meta.url)), '..')

function read(rel: string): string {
  return readFileSync(join(src, rel), 'utf8')
}

test('salonHours does not import owner.ts', () => {
  expect(read('lib/salonHours.ts')).not.toMatch(/from '\.\/owner'/)
})

test('salon profile stack is address, empty aside split, then hours/services', () => {
  const page = read('pages/SalonProfile.tsx')
  const catalogStart = page.indexOf('  const catalog =')
  const viewStart = page.lastIndexOf('\n  return (')
  const catalog = page.slice(catalogStart, viewStart)
  const view = page.slice(viewStart)

  const nameAt = view.indexOf('{salon.name}')
  const addressAt = view.indexOf('{addressLine}')
  const splitAt = view.indexOf('SALON_BOOKING_SPLIT_CLASS')
  const asideAt = view.indexOf('SALON_BOOKING_ASIDE_CLASS')
  const catalogUseAt = view.indexOf('SALON_BOOKING_MAIN_CLASS}>{catalog}')
  const successAt = view.indexOf("t('salon.success')")
  const dialogAt = view.indexOf('<dialog')

  expect(nameAt).toBeGreaterThan(-1)
  expect(addressAt).toBeGreaterThan(nameAt)
  expect(splitAt).toBeGreaterThan(addressAt)
  expect(asideAt).toBeGreaterThan(splitAt)
  expect(catalogUseAt).toBeGreaterThan(asideAt)
  expect(successAt).toBeGreaterThan(catalogUseAt)
  expect(dialogAt).toBeGreaterThan(successAt)

  expect(view).toMatch(/showBookingColumn \?/)
  expect(page).toMatch(/const showBookingColumn = hasServices && !sent/)
  expect(view).toMatch(/aria-hidden="true"/)
  expect(view).not.toMatch(/hasServices && !picking && !sent/)

  const hoursAt = catalog.indexOf("t('salon.hours')")
  const hintAt = catalog.indexOf("t('salon.sendHint')")
  const hoursMapAt = catalog.indexOf('salon.hours.map')
  const servicesAt = catalog.indexOf("t('salon.services')")
  expect(hoursAt).toBeGreaterThan(-1)
  expect(hintAt).toBeGreaterThan(hoursAt)
  expect(hoursMapAt).toBeGreaterThan(hintAt)
  expect(servicesAt).toBeGreaterThan(hoursMapAt)
  expect(catalog).toMatch(/showBookingColumn \? undefined : 'mt-8'/)
  expect(catalog).toMatch(/picking=\{false\}/)
  expect(catalog).toMatch(/showDaySendPill/)
  expect(catalog).toMatch(/assistant\.ask/)
  expect(catalog).toMatch(/SALON_CHAT_CARD_CLASS/)

  const mapStart = hoursMapAt
  const mapEnd = catalog.indexOf('</ul>')
  const hoursMap = catalog.slice(mapStart, mapEnd)
  expect(hoursMap).toMatch(/SALON_SEND_CLASS/)
  expect(hoursMap).toMatch(/openIntake\('picker'\)/)
  expect(hoursMap).not.toMatch(/max-w-md/)
  const afterList = catalog.slice(mapEnd)
  expect(afterList).toMatch(/SALON_CHAT_CARD_CLASS/)
  expect(afterList).not.toMatch(/SALON_SEND_CLASS/)
  expect(afterList).not.toMatch(/showSendPill/)

  expect(page).toMatch(/SalonServiceGroups/)
  expect(page).toMatch(/svc-cat-\$\{group\.id\}/)
  expect(page).toMatch(/hidden w-40 shrink-0 md:block/)
  expect(page).toMatch(/visible\.length >= 2/)
  expect(page).not.toMatch(/category\.\$\{/)
})

test('address is optional text line; no maps', () => {
  const page = read('pages/SalonProfile.tsx')
  expect(page).toMatch(/assistantAddressLine\(salon\.address\)/)
  expect(page).toMatch(/addressLine !== null \? <p className="mt-3 text-sm text-muted">\{addressLine\}<\/p>/)
  expect(page).not.toMatch(/Adresa/)
  expect(page).not.toMatch(/maps\.google/)
  expect(page).not.toMatch(/\blat\b|\blng\b/)
})

test('public salon query stays photoless', () => {
  const query = read('graphql/salon.ts')
  expect(query).not.toMatch(/description/)
  expect(query).not.toMatch(/mainImageUrl/)
  expect(query).not.toMatch(/galleryUrls/)
})

test('aside stays empty; send pill is under hours after a day', () => {
  const page = read('pages/SalonProfile.tsx')
  const asideStart = page.indexOf('<aside className={SALON_BOOKING_ASIDE_CLASS}')
  const asideEnd = page.indexOf('<div className={SALON_BOOKING_MAIN_CLASS}>{catalog}</div>')
  const aside = page.slice(asideStart, asideEnd)
  expect(aside).toMatch(/aria-hidden="true"/)
  expect(aside).not.toMatch(/salon\.send/)
  expect(aside).not.toMatch(/salon\.sendHint/)
  expect(aside).not.toMatch(/assistant\.ask/)
  expect(aside).not.toMatch(/SALON_SEND_CLASS/)
  expect(page).toMatch(/showDaySendPill/)
  expect(page).toMatch(/openIntake\('picker'\)/)
  expect(page).not.toMatch(/setScrollPicker/)
  expect(page).toMatch(/<dialog/)
  expect(page).toMatch(/SALON_PICKER_DIALOG_CLASS/)
  expect(page).toMatch(/showModal/)
  expect(page).toMatch(/CREATE_BOOKING_MUTATION/)
  expect(page).toMatch(/chatDialogRef/)
})

test('sendHint lives under Radno vrijeme; chat is a card not an underline', () => {
  const page = read('pages/SalonProfile.tsx')
  const catalogStart = page.indexOf('  const catalog =')
  const viewStart = page.lastIndexOf('\n  return (')
  const catalog = page.slice(catalogStart, viewStart)
  expect(catalog).toMatch(/salon\.sendHint/)
  expect(catalog).toMatch(/assistant\.nudge/)
  expect(catalog).toMatch(/SALON_CHAT_CARD_CLASS/)
  expect(catalog).toMatch(/pointer-events-none/)
  expect(catalog).toMatch(/aria-pressed/)
  expect(catalog).not.toMatch(/<AssistantIntake/)
  expect(catalog).not.toMatch(/underline underline-offset-4[\s\S]*assistant\.ask/)

  const asideStart = page.indexOf('<aside className={SALON_BOOKING_ASIDE_CLASS}')
  const asideEnd = page.indexOf('<div className={SALON_BOOKING_MAIN_CLASS}>{catalog}</div>')
  const aside = page.slice(asideStart, asideEnd)
  expect(aside).not.toMatch(/salon\.sendHint/)

  const chat = read('components/AssistantIntake.tsx')
  expect(chat).not.toMatch(/salon\.sendHint/)
  expect(chat).toMatch(/assistant\.prompt/)
  expect(chat).toMatch(/ASSISTANT_SALON_LINE_CLASS/)
  expect(chat).toMatch(/ASSISTANT_GUEST_PILL_CLASS/)
  expect(chat).toMatch(/ASSISTANT_COMPOSER_CLASS/)
  expect(chat).toMatch(/flex flex-wrap/)
  expect(chat).not.toMatch(/min-h-\[70dvh\]/)
  expect(chat).not.toMatch(/rounded-3xl bg-ink/)
  expect(chat).not.toMatch(/<textarea/)
  expect(chat).not.toMatch(/esyres-mark/)
})

test('hours rows use helpers; closed is muted; chat tap does not copy intake', () => {
  const page = read('pages/SalonProfile.tsx')
  expect(page).toMatch(/hoursRowClosed/)
  expect(page).toMatch(/hoursRowTappable/)
  expect(page).toMatch(/hoursRowSelected/)
  expect(page).toMatch(/applyHoursRowTap/)
  expect(page).toMatch(/type="button"/)
  expect(page).toMatch(/text-muted/)
  expect(page).toMatch(/hover:bg-surface-soft/)
  expect(page).toMatch(/focus:bg-surface-soft/)
  expect(page).toMatch(/bg-surface-soft/)
  expect(page).not.toMatch(/md:grid-cols-2/)

  const asideStart = page.indexOf('<aside className={SALON_BOOKING_ASIDE_CLASS}')
  const asideEnd = page.indexOf('<div className={SALON_BOOKING_MAIN_CLASS}>{catalog}</div>')
  const aside = page.slice(asideStart, asideEnd)
  expect(aside).not.toMatch(/hoursRowClosed|salon\.hours|weekday/)

  const tapStart = page.indexOf('function onHoursTap')
  const tapEnd = page.indexOf('function bookingInput')
  const tap = page.slice(tapStart, tapEnd)
  expect(tap).toMatch(/applyHoursRowTap/)
  expect(tap).not.toMatch(/openIntake\('picker'\)/)
  expect(tap).toMatch(/setPreferredDate\(next\.preferredDate\)/)
  expect(tap).toMatch(/if \(chatting\)/)
  expect(tap).toMatch(/setMode\('idle'\)/)
  expect(tap).not.toMatch(/chatSelected|setChatDate|setChatTime|setChatWorker|clearIntakeToken|pingIntake|onPing/)
})

test('pill opens picker modal; chat card opens a second dialog', () => {
  const page = read('pages/SalonProfile.tsx')
  expect(page).not.toMatch(/pickerFormRef = useRef<HTMLFormElement>\(null\)/)
  expect(page).not.toMatch(/scrollIntoView/)
  expect(page).toMatch(/pickerDialogRef = useRef<HTMLDialogElement>\(null\)/)
  expect(page).toMatch(/chatDialogRef = useRef<HTMLDialogElement>\(null\)/)
  expect(page.match(/<dialog/g)?.length).toBe(2)
  expect(page.match(/className=\{SALON_PICKER_DIALOG_CLASS\}/g)?.length).toBe(2)
  expect(page).toMatch(/openIntake\('chat'\)/)
  expect(page).toMatch(/type="button"[\s\S]*className=\{SALON_SEND_CLASS\}[\s\S]*openIntake\('picker'\)/)
  expect(page).toMatch(/setMode\('chat'\)/)
  expect(page).not.toMatch(/formatOwnerDayHeading/)
  const pickerDialog = page.slice(page.indexOf('<dialog'), page.lastIndexOf('<dialog'))
  expect(pickerDialog).toMatch(/\{salon\.name\}/)
  expect(pickerDialog).toMatch(/weekday\./)
  expect(pickerDialog).toMatch(/formatPickerDayNumeric/)
  expect(pickerDialog).toMatch(/onChange=\{\(e\) => setPreferredDate\(e\.target\.value\)\}/)
  expect(pickerDialog).not.toMatch(/onChange=\{\(e\) => \{[\s\S]*setMode/)
  expect(pickerDialog).toMatch(/type="date"/)
  expect(pickerDialog).toMatch(/type="time"/)
  expect(pickerDialog).toMatch(/onCancel/)
  expect(pickerDialog).toMatch(/dialogCancelShouldClose/)
  expect(pickerDialog).toMatch(/preventDefault/)
  expect(pickerDialog).toMatch(/showModal/)
  expect(pickerDialog).toMatch(/setMode\('idle'\)/)
  expect(pickerDialog).not.toMatch(/onCancel=\{\(e(?:vent)?\) => e(?:vent)?\.preventDefault\(\)\}/)
  const chatDialog = page.slice(page.lastIndexOf('<dialog'))
  expect(chatDialog).toMatch(/<AssistantIntake/)
  expect(chatDialog).toMatch(/salon\.close/)
  expect(chatDialog).not.toMatch(/<h2[\s\S]*\{salon\.name\}/)
  expect(chatDialog).not.toMatch(/formatPickerDayNumeric/)
  expect(chatDialog).not.toMatch(/nav\.welcome/)
  expect(chatDialog).toMatch(/mode === 'chat'/)
  expect(chatDialog).toMatch(/onCancel/)
  expect(chatDialog).toMatch(/dialogCancelShouldClose/)
  expect(chatDialog).toMatch(/preventDefault/)
  expect(chatDialog).toMatch(/showModal/)
  expect(chatDialog).toMatch(/setMode\('idle'\)/)
  const chat = read('components/AssistantIntake.tsx')
  expect(chat).toMatch(/type="date"/)
  expect(chat).toMatch(/type="time"/)
})

test('loading and missing salon skip the booking split', () => {
  const page = read('pages/SalonProfile.tsx')
  const loading = page.slice(page.indexOf('if (loading)'), page.indexOf('const salon = data?.salon'))
  expect(loading).toMatch(/GUEST_COLUMN_CLASS/)
  expect(loading).not.toMatch(/SALON_BOOKING_SPLIT_CLASS/)
  const missing = page.slice(page.indexOf('if (!salon)'), page.indexOf('const token = busyToken'))
  expect(missing).toMatch(/GUEST_COLUMN_CLASS/)
  expect(missing).not.toMatch(/SALON_BOOKING_SPLIT_CLASS/)
})
