// @ts-nocheck — Node fs is not in the PWA tsconfig; Vitest runs this file.
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { expect, test } from 'vitest'

const src = join(dirname(fileURLToPath(import.meta.url)), '..')

function read(rel: string): string {
  return readFileSync(join(src, rel), 'utf8')
}

test('salonHours does not import owner.ts', () => {
  expect(read('lib/salonHours.ts')).not.toMatch(/from '\.\/owner'/)
})

test('salon profile stack is address, empty aside, read-only hours, then the send pill, then services', () => {
  const page = read('pages/SalonProfile.tsx')
  const catalogStart = page.indexOf('  const catalog =')
  const viewStart = page.lastIndexOf('\n  return (')
  const catalog = page.slice(catalogStart, viewStart)
  const view = page.slice(viewStart)
  const beforeDialog = view.slice(0, view.indexOf('<dialog'))

  const nameAt = view.indexOf('{salon.name}')
  const addressAt = view.indexOf('{addressLine}')
  const splitAt = view.indexOf('SALON_BOOKING_SPLIT_CLASS')
  const asideAt = view.indexOf('SALON_BOOKING_ASIDE_CLASS')
  const catalogUseAt = view.indexOf('SALON_BOOKING_MAIN_CLASS}>{catalog}')

  expect(nameAt).toBeGreaterThan(-1)
  expect(addressAt).toBeGreaterThan(nameAt)
  expect(splitAt).toBeGreaterThan(addressAt)
  expect(asideAt).toBeGreaterThan(splitAt)
  expect(catalogUseAt).toBeGreaterThan(asideAt)
  expect(beforeDialog).not.toMatch(/salon\.success/)

  expect(view).toMatch(/showBookingColumn \?/)
  expect(page).toMatch(/const showBookingColumn = hasServices/)
  expect(page).not.toMatch(/const showBookingColumn = hasServices && !sent/)
  expect(view).toMatch(/aria-hidden="true"/)

  const hoursAt = catalog.indexOf("t('salon.hours')")
  const hoursMapAt = catalog.indexOf('salon.hours.map')
  const listEnd = catalog.indexOf('</ul>')
  const servicesAt = catalog.indexOf("t('salon.services')")
  const hoursMap = catalog.slice(hoursMapAt, listEnd)
  const afterList = catalog.slice(listEnd, servicesAt)

  expect(hoursAt).toBeGreaterThan(-1)
  expect(hoursMapAt).toBeGreaterThan(hoursAt)
  expect(servicesAt).toBeGreaterThan(listEnd)
  expect(catalog).not.toMatch(/salon\.sendHint/)
  expect(catalog).toMatch(/picking=\{false\}/)
  expect(hoursMap).not.toMatch(/<button/)
  expect(hoursMap).not.toMatch(/SALON_SEND_CLASS/)
  expect(hoursMap).not.toMatch(/onHoursTap|showDaySendPill|hoursRowTappable|hoursRowSelected/)
  expect(afterList).toMatch(/hasServices \?/)
  expect(afterList).toMatch(/SALON_SEND_CLASS/)
  expect(afterList).toMatch(/openPicker/)
  expect(afterList).not.toMatch(/createBooking/)
  expect(catalog).not.toMatch(/assistant\.ask|SALON_CHAT_CARD_CLASS/)

  expect(page).toMatch(/SalonServiceGroups/)
  expect(page).toMatch(/svc-cat-\$\{group\.id\}/)
  expect(page).toMatch(/hidden w-40 shrink-0 md:block/)
  expect(page).toMatch(/visible\.length >= 2/)
  expect(page).not.toMatch(/category\.\$\{/)
})

test('address is optional text line; no maps', () => {
  const page = read('pages/SalonProfile.tsx')
  expect(page).toMatch(/assistantAddressLine\(salon\.address\)/)
  expect(page).toMatch(/addressLine !== null \? <p className="mt-3 text-sm text-muted">\{addressLine\}<\/p>/)
  expect(page).not.toMatch(/Adresa/)
  expect(page).not.toMatch(/maps\.google/)
  expect(page).not.toMatch(/\blat\b|\blng\b/)
})

test('public salon query stays photoless', () => {
  const query = read('graphql/salon.ts')
  expect(query).not.toMatch(/description/)
  expect(query).not.toMatch(/mainImageUrl/)
  expect(query).not.toMatch(/galleryUrls/)
})

test('aside stays empty; profile does not open chat', () => {
  const page = read('pages/SalonProfile.tsx')
  const asideStart = page.indexOf('<aside className={SALON_BOOKING_ASIDE_CLASS}')
  const asideEnd = page.indexOf('<div className={SALON_BOOKING_MAIN_CLASS}>{catalog}</div>')
  const aside = page.slice(asideStart, asideEnd)
  expect(aside).toMatch(/aria-hidden="true"/)
  expect(aside).not.toMatch(/salon\.send/)
  expect(aside).not.toMatch(/SALON_SEND_CLASS/)
  expect(aside).not.toMatch(/hoursRowClosed|salon\.hours|weekday/)
  expect(page).not.toMatch(/<AssistantIntake|chatDialogRef|setMode\('chat'\)|openIntake\('chat'\)/)
  expect(page.match(/<dialog/g)?.length).toBe(1)
  expect(read('components/AssistantIntake.tsx').length).toBeGreaterThan(0)
})

test('hours rows are read-only; closed stays muted', () => {
  const page = read('pages/SalonProfile.tsx')
  expect(page).toMatch(/hoursRowClosed/)
  expect(page).toMatch(/hoursLine/)
  expect(page).toMatch(/flex justify-between/)
  expect(page).toMatch(/text-muted/)
  expect(page).not.toMatch(/onHoursTap|applyHoursRowTap|hover:bg-surface-soft|bg-surface-soft/)
  expect(page).not.toMatch(/openWeekday|hoursAccordionSummary/)
})

test('picker opens from the pill, names the day, and only Zatvori dismisses', () => {
  const page = read('pages/SalonProfile.tsx')
  const dialog = page.slice(page.indexOf('<dialog'))
  expect(page).toMatch(/pickerDialogRef = useRef<HTMLDialogElement>\(null\)/)
  expect(page).toMatch(/SALON_PICKER_DIALOG_CLASS/)
  expect(page).toMatch(/showModal/)
  expect(page).toMatch(/CREATE_BOOKING_MUTATION/)
  expect(page).not.toMatch(/formatOwnerDayHeading/)
  expect(page).not.toMatch(/owner\.phone\.today/)
  expect(page).not.toMatch(/type="time"/)
  expect(page).not.toMatch(/dialogCancelShouldClose/)
  expect(dialog).toMatch(/\{salon\.name\}/)
  expect(dialog).toMatch(/text-sm text-muted/)
  expect(dialog).toMatch(/weekday\./)
  expect(dialog).toMatch(/formatPickerDayNumeric/)
  expect(dialog).toMatch(/preferredDate !== ''/)
  expect(dialog).toMatch(/salon\.today/)
  expect(dialog).toMatch(/salon\.tomorrow/)
  expect(dialog).toMatch(/salon\.otherDay/)
  expect(dialog).toMatch(/aria-pressed/)
  expect(dialog).toMatch(/rounded-full bg-ink/)
  expect(dialog).toMatch(/flex flex-wrap gap-2/)
  expect(dialog).toMatch(/type="date"/)
  expect(dialog).toMatch(/min=\{date\}/)
  expect(dialog).toMatch(/onChange=\{\(event\) => applyDay\(\{ date: event\.target\.value \}\)\}/)
  expect(dialog).not.toMatch(/onChange=\{[^}]*setMode/)
  expect(dialog).toMatch(/salon\.noPreference/)
  expect(dialog).toMatch(/chosen\.length > 0 && preferredDate !== ''/)
  expect(dialog).toMatch(/salon\.quarter\.booked/)
  expect(dialog).toMatch(/salon\.quarter\.none/)
  expect(dialog).toMatch(/salon\.quarter\.dayOnly/)
  expect(dialog).toMatch(/text-muted/)
  expect(page).toMatch(/const canSendPicker = chosen\.length > 0 && preferredDate !== '' && !pickerClosed/)
  expect(dialog).toMatch(/salon\.gate\.SALON_CLOSED/)
  expect(dialog).not.toMatch(/PillsSkeleton/)
  expect(page).toMatch(/QUARTER_STARTS_QUERY/)
  expect(page).toMatch(/quartersLoading/)
  expect(page).toMatch(/guestAfterServiceChange/)
  expect(page).not.toMatch(/PillsSkeleton/)
  expect(dialog).toMatch(/onCancel=\{\(event\) => \{\s*event\.preventDefault\(\)/)
  expect(dialog).toMatch(/allowClose/)
  expect(dialog).toMatch(/showModal/)
  expect(dialog).not.toMatch(/onClick=\{\(event\) => \{[\s\S]*setMode\('idle'\)/)
  expect(page).toMatch(/function closePicker\(\) \{\s*allowClose\.current = true/)
  expect(dialog).toMatch(/onClick=\{closePicker\}/)
  expect(dialog).toMatch(/t\('salon\.success'\)/)
  expect(dialog).toMatch(/t\('salon\.close'\)/)
})

test('skip runs on open; day change clears worker; login does not send', () => {
  const page = read('pages/SalonProfile.tsx')
  const openStart = page.indexOf('function openPicker')
  const openEnd = page.indexOf('function closePicker')
  const open = page.slice(openStart, openEnd)
  expect(open).toMatch(/guestHoursSkip/)
  expect(open).not.toMatch(/createBooking/)

  const toggleStart = page.indexOf('function toggle')
  const toggleEnd = page.indexOf('function applyDay')
  expect(page.slice(toggleStart, toggleEnd)).not.toMatch(/guestHoursSkip/)

  const applyStart = page.indexOf('function applyDay')
  const applyEnd = page.indexOf('function openPicker')
  const apply = page.slice(applyStart, applyEnd)
  expect(apply).toMatch(/guestDayChange/)
  expect(apply).toMatch(/setWorkerChoice\(next\.workerId\)/)
  expect(apply).toMatch(/setPreferredTime\(next\.time\)/)
  expect(apply).not.toMatch(/guestHoursSkip/)

  expect(page).toMatch(/meData\?\.me == null[\s\S]*salon\.loginToRequest[\s\S]*AuthShell/)
  expect(page).toMatch(/onAuthenticated=\{\(\) => setNeedLogin\(false\)\}/)
  const sendStart = page.indexOf('async function send')
  const unauthAt = page.indexOf("code === 'UNAUTHENTICATED'", sendStart)
  const emailAt = page.indexOf("code === 'EMAIL_UNVERIFIED'", unauthAt)
  const unauth = page.slice(unauthAt, emailAt)
  expect(unauth).toMatch(/setNeedLogin\(true\)/)
  expect(unauth).not.toMatch(/setSelected|setPreferredDate|setWorkerChoice|setMode\('idle'\)/)
  expect(page).toMatch(/SAME_DAY_SERVICE/)
  expect(page).toMatch(/function onVerified/)
  expect(page.slice(page.indexOf('function onVerified'), page.indexOf('const catalog'))).toMatch(/canSendPicker[\s\S]*send\(input\)/)
  const sent = page.slice(page.indexOf('await createBooking'), page.indexOf('} catch'))
  expect(sent).toMatch(/setSent\(true\)/)
  expect(sent).not.toMatch(/setMode\('idle'\)/)
})

test('loading and missing salon skip the booking split', () => {
  const page = read('pages/SalonProfile.tsx')
  const loading = page.slice(page.indexOf('if (loading)'), page.indexOf('const salon = data?.salon'))
  expect(loading).toMatch(/<GuestPageSkeleton>/)
  expect(loading).not.toMatch(/SALON_BOOKING_SPLIT_CLASS/)
  const missing = page.slice(page.indexOf('if (!salon)'), page.indexOf('const token = busyToken'))
  expect(missing).toMatch(/GUEST_COLUMN_CLASS/)
  expect(missing).not.toMatch(/SALON_BOOKING_SPLIT_CLASS/)
})
